[package]
name = "argwerk"
version = "0.18.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]
repository = "https://github.com/udoprog/argwerk"
homepage = "https://github.com/udoprog/argwerk"
documentation = "https://docs.rs/argwerk"
description = """
Simple command-line parser through a declarative macro.
"""

[dev-dependencies]
anyhow = "1"
